version: "3"

services:
  mba_web:
    image: node:latest
    tty: true
    stdin_open: true
    working_dir: /app
    command: bash -c "while true; do sleep 60; done"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
